send task to runrunit
PetBookingBrasil/bino pull request #4
Opened 2019-03-14 16:50 UTC by LucasHatze

https://runrun.it/pt-BR/tasks/241

2019-04-04 18:40 UTC, douglasandre requested changes

2019-04-04 18:40 UTC, douglasandre commented on spec/models/task_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
@LucasHatze  faltou os specs aqui... Devia ter começado com eles, inclusive..

2019-04-04 18:40 UTC, douglasandre commented on spec/models/agent_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
@LucasHatze faltou os specs aqui... Devia ter começado com eles, inclusive..

2019-04-04 18:40 UTC, douglasandre commented on app/services/converters/ticket_to_task.rb
> +      {
Falta um rspec pra esse cara né?

2019-04-04 18:40 UTC, douglasandre commented on app/services/runrunit/runrunit_exporter.rb
> +      body = { task: Converters::TicketToTask.new(@ticket).convert }
Esse cara aqui também precisava de um teste.

2019-04-04 18:40 UTC, douglasandre commented on app/services/zendesk/zendesk_importer.rb
> +      last_date = @agent.last_sync.try(:strftime, "%Y-%m-%d") || 1.year.ago.strftime("%Y-%m-%d")
O ideal é que ele não traga os tickets passados... Tickets de um ano atrás, por exemplo já foram resolvidos. O padrão deveria ser tickets que forem criados da data de hoje para frente... EX: cartão criado hoje de manhã, ele traz, cartão criado ontem não...

2019-04-04 18:40 UTC, douglasandre commented on config/initializers/cors.rb
> +    origins '*'
Liberar acesso de qualquer domínio/IP para esse serviço é perigoso..
Já pensou uma pessoa má intencionada consumindo recursos desse serviço?

2019-04-04 18:40 UTC, douglasandre commented on db/migrate/20190228203432_create_tasks.rb
> +      t.references :source
O source, destiny, e id's nos respectivos providers não poderiam ser nulos certo?

2019-04-04 18:40 UTC, douglasandre commented on app/services/runrunit/resources.rb
> +
É questão de estética, mas essas linhas em branco são completamente fora do padrão... Sugiro executar um rubocop aqui só pra ver.

2019-04-05 12:03 UTC, LucasHatze commented on app/services/converters/ticket_to_task.rb
> +      {
@douglasandre acredito que essa parte seja do @m4nn0l0, eu apenas faria o envio das tasks para o runrunit

2019-04-05 12:03 UTC, LucasHatze commented on app/services/runrunit/resources.rb
> +
!

2019-04-05 12:03 UTC, LucasHatze commented on app/services/runrunit/runrunit_exporter.rb
> +      body = { task: Converters::TicketToTask.new(@ticket).convert }
!

2019-04-05 12:03 UTC, LucasHatze commented on app/services/zendesk/zendesk_importer.rb
> +      last_date = @agent.last_sync.try(:strftime, "%Y-%m-%d") || 1.year.ago.strftime("%Y-%m-%d")
@douglasandre essa parte foi feita pelo @foolem, mas acredito que ele traga apenas os tickets que ainda não foram importados para o sistema. Ex: caso o ultimo sync tenha sido feito ontem as 22h ele ira trazer no próximo sync todos os tickets criados a partir das 22h

2019-04-05 12:03 UTC, LucasHatze commented on config/initializers/cors.rb
> +    origins '*'
@foolem

2019-04-05 12:03 UTC, LucasHatze commented on db/migrate/20190228203432_create_tasks.rb
> +      t.references :source
@foolem

2019-04-05 12:03 UTC, LucasHatze commented on spec/models/agent_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
@foolem

2019-04-05 12:03 UTC, LucasHatze commented on spec/models/task_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
@foolem

2019-04-09 18:54 UTC, closed without merging