Refactored project
PetBookingBrasil/bino pull request #5
Opened 2019-04-05 21:57 UTC by foolem

2019-04-09 14:44 UTC, LucasHatze commented on app/services/bino_service.rb
> +    raise "Rejected type" if !SOURCE_TYPES.include?(@source_type) || !DESTINY_TYPES.include?(@destiny_type)
@foolem nesse caso não seria mais viável utilizar o unless?

2019-04-09 14:48 UTC, maunolo approved these changes

2019-04-10 20:07 UTC, douglasandre requested changes
Alguns ajustes pra gente fazer time!

2019-04-10 20:07 UTC, douglasandre commented on Gemfile
> +gem "zendesk_api"
Poxa que massa que já tem uma gem do Zendesk! Isso ajuda muito. Quando não temos nenhum código ruby no meio, usar sempre aspas simples.

2019-04-10 20:07 UTC, douglasandre commented on app/models/bino_package.rb
> +  validates :source, :destiny, presence: true
Essas validações e enums deveriam estar todos contemplados em um rspec. Model sempre precisa ter um spec, mesmo sendo conceitual.

2019-04-10 20:07 UTC, douglasandre commented on app/services/bino_service.rb
> +    source_class = "Agents::#{@source.capitalize}Service".constantize
Pessoal, lembram da talk de segurança? `constantize` e `send` são perigosos em termos de segurança.. Cuidado!
http://gavinmiller.io/2016/the-safesty-way-to-constantize/

2019-04-10 20:07 UTC, douglasandre commented on app/services/agents/runrunit_service.rb
> +      resource = "api/v1.0/#{destiny_type == 'card' ? 'tasks' : '' }"
Acredito que para deixar essa linha um pouco mais reutilizável, e já definirmos um padrão a ser compartilhado por todos os agents futuros podemos:

1. Definir uma constante, com a base da API. Algo como: API_BASE_URL='api/v1.0/'. Isso vai permitir que a variável seja facilmente compartilhada por ações futuras e vai definir um padrão a sempre ser seguido pelos agents.
2. O destiny_type pelo que vimos já deveria vir correto. Caso seja necessário fazer uma "tradução" do tipo recebido, para o esperado pelo provedor do destino, acredito que a melhor opção seja trabalhar com isso em um método privado para: permitir o compartilhamento com ações futuras, e deixar a ação de post mais "verbosa" e simples.

2019-04-10 20:07 UTC, douglasandre commented on app/services/agents/runrunit_service.rb
> +class Agents::RunrunitService
Por se tratar de algo novo, acho bacana seguirmos o padrão do rubocop.

2019-04-10 20:07 UTC, douglasandre commented on app/services/agents/runrunit_service.rb
> +      BinoPackage.find_by(external_source_id: obj[:id])
Imagino que essa linha vai se espalhar por todos os agents do projeto...
Acredito que o ideal, seja manter centralizado no service do Bino, assim ela não será copiada pelos demais Agents.

2019-04-10 20:07 UTC, douglasandre commented on app/services/agents/zendesk_service.rb
> +class Agents::ZendeskService
Padrão do Rubocop.

2019-04-10 20:07 UTC, douglasandre commented on app/services/agents/zendesk_service.rb
> +    last_date = BinoPackage.where(source: "zendesk", package_type: destiny_type, status: :sent)
Eu imagino que esse carregamento da última data de sync vai estar "pulverizado" em todos os agents não?
Acredito que temos algumas alternativas nesse caso:
1. Criar um AgentBase, que tem um método que carrega o last_date e deixa isso automaticamente acessóvel a todo e qualquer agent sem necessidade de replicar código.
2. Deixar todo o carregamento/manipulação de Pacotes no BinoService.

A ideia é termos Agents o mais enxutos possíveis, para ser o mais simples e rápido possível criar e integrar novos serviços.

2019-04-10 20:07 UTC, douglasandre commented on app/services/agents/zendesk_service.rb
> +      BinoPackage.create(source: "zendesk",
A criação de um pacote também é algo que eu deixaria centralizado. Esse trecho de código em específico, acredito que o ideal seria deixar no BinoService mesmo...
O agent só carrega os objetos dele, e passa a bola para o bino, que ele se encarregue de criar os pacotes...

2019-04-10 20:07 UTC, douglasandre commented on app/services/bino_service.rb
> +  SOURCE_TYPES = ["ticket", "card"]
Pelo que  vimos no source deveríamos ter apenas 'ticket'.

2019-04-10 20:07 UTC, douglasandre commented on app/services/bino_service.rb
> +  DESTINY_TYPES = ["ticket", "card"]
Pelo que vimos no destiny deveríamos ter apenas 'task'.

2019-04-10 20:07 UTC, douglasandre commented on app/services/bino_service.rb
> +    @source = source
Se quiser, você pode fazer essas atribuições em uma linha só também...
ex:
```
@source, @destiny, @source_type = source, destiny, source_type
```

2019-04-10 20:07 UTC, douglasandre commented on app/services/bino_service.rb
> +    raise "Rejected type" if !SOURCE_TYPES.include?(@source_type) || !DESTINY_TYPES.include?(@destiny_type)
Estou contigo nessa @LucasHatze. `if !` sempre pode virar um `unless` a não ser que tenha uma negativa no meio, aí confunde. 😄

2019-04-10 20:07 UTC, douglasandre commented on app/services/agents/zendesk_service.rb
> +      Converters::TicketToTask.convert(objects)
Uma das coisas que reparei no runrun.it é que algumas tasks estavam sendo criadas sem um título. Apenas: "[Zendesk] - "
Acho importante validarmos esse envio em algum lugar... Talvez no próprio agent, no momento de fazer o post, ele pode apenas sinalizar se o registro em questão é ou não válido para envio.
Caso o registro não seja válido sinalizamos isso no package através de um status como: "invalid", por exemplo.

2019-04-10 20:07 UTC, douglasandre commented on app/services/resources/runrunit.rb
> +class Resources::Runrunit
Atentar para o padrão do rubocop

2019-04-10 20:07 UTC, douglasandre commented on app/services/resources/runrunit.rb
> +
Linhas em branco...

2019-04-10 20:07 UTC, douglasandre commented on lib/tasks/bino.rake
> +  task :init, [:source, :destiny, :source_type, :destiny_type, :object_id] => [:environment] do |task, args|
Qual linha deveria ser colocada num scheduler para importar as tasks do Zendesk?
```
bino:init......
```

2019-04-10 20:07 UTC, douglasandre commented on spec/services/agents/runrunit_service_spec.rb
> +  let!(:response_id) { "1" }
Alguma razão especial para o `!` ?

2019-04-10 20:07 UTC, douglasandre commented on spec/services/agents/runrunit_service_spec.rb
> +    BinoPackage.create(source: "zendesk", destiny: "runrunit", external_source_id: 1)
aspas simples

2019-04-10 20:07 UTC, douglasandre commented on spec/services/bino_spec.rb
> +      expect(subject.instance_variable_get(:@source)).not_to be_nil
Dá pra fazer um array com as variáveis que você quer checar, e montar os testes dentro de um bloco... ex:
```
%w(source destiny source_type).each do |variable_name|
      it "assigns #{variable_name} variable" do
          expect(subject.instance_variable_get(variable_name)).not_to be_nil
      end
end
```

2019-04-10 20:07 UTC, douglasandre commented on spec/services/bino_spec.rb
> +  context 'when source or destiny is invalid' do
Está faltando um context aqui não? O que acontece quando eu chamo transport com os parâmetros corretos?

2019-04-10 20:07 UTC, douglasandre commented on spec/services/agents/runrunit_service_spec.rb
> +    it "updates BinoPackage with response id" do
Como comentei, eu deixaria essa manipulação dos pacotes em um base, ou no serviço principal do bino...
Deixaria os agents o mais enxutos possível para reduzir nosso trabalho no futuro :P

2019-04-26 19:49 UTC, closed without merging